config/routes.rb
Rails.application.routes.draw do
  # get 'books/index'
  # get 'books/show'
  # get 'books/new'
  # get 'books/update'
  # get 'books/destroy'
  resources :books
  
  get 'users' => 'users#index'
  get 'users/:id' => 'users#show'
  post 'user' => 'users#create'
  put 'user/:id' => 'users#update'
  delete 'user/:id' => 'users#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/school.rb
class School < ApplicationRecord
    has_many :student
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :user
    belongs_to :school
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  # def show
  # end

  # def new
  # end

  # def update
  # end

  # def destroy
  # end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
    def index 
        @schools = School.all
    end

    def create
        @school = School.new(school_params)
        if @school.save
            render json: {
                status: true
            }
        else
            render json: {
                status: false
            }
        end
    end

    def destroy
        @school = School.find(params[:id])
        if @school.destroy
            render json: {
                status: true
            }
        else
            render json: {
                status: false
            }
        end
    end

    private
    def school_params
        params.permit(:school_number, :name, :address)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def index
        @students = Student.all
        respond_to do |format|
            format.html
            format.json {
                render :json => @students.to_json(:include => { :user => {:only => [:name, :phone_number, :address]} })
            }
        end
        @users = User.all
        @schools = School.all
    end

    def create
        @student = Student.new(student_params)
        if @student.save
            render json: {
                status: true
            }
        else
            render json: {
                status: false
            }
        end
    end

    def destroy
        @student = Student.find(params[:id])
        if @student.destroy
            render json: {
                status: true
            }
        else
            render json: {
                status: false
            }
        end
    end

    private
    def student_params
        params.permit(:nis, :user_id, :school_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    # skip_before_filter :verify_authenticity_token
    # rescue_from ActiveRecord::RecordNotFound, with: :notFound

    def index
        @users = User.all
        render json:{
            values: @users,
            message: 'success',
        }, status: 200
    end
    def show
        @user = User.find_by_id(params[:id])
        if @user.present?
            render json: {
                values: @user,
                message: 'success'
            }, status: 200
        else
            render json: {
                values: '',
                message: 'Data null'
            }, status: 400
        end
    end
    def create
        @user = User.new(user_params)
        if @user.save
            render json: {
                values: '',
                message: 'success'
            }, status: 200
        else
            render json: {
                values: '',
                message: 'Fail'
            }, status: 400
        end
    end
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            render json: {
                values: '',
                message: 'success'
            }, status: 200
        else
            render json: {
                values: '',
                message: 'Fail'
            }, status: 400
        end
    end
    def destroy
        @user = User.find(params[:id])
        if @user.destroy
            render json: {
                values: '',
                message: 'success'
            }, status: 200
        else
            render json: {
                values: '',
                message: 'Fail'
            }, status: 400
        end
    end
    private
        def user_params
            params.permit(:name, :phone, :address)
        end

        def notFound
            render json:{
                values: '',
                message: 'Data not found'
            }, status: 400
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learnruby1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schools/index.html.erb
<%= render 'templates/navigation' %>
<div class="container p-4">
    <h2>Data SChools</h2>
    <div class="card">
        <div class="card-header">  
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#new_school" id="button">Add New School</button>
        </div>
        <div class="card-body">
            <table class="table table_schools">
                <thead>
                <tr>
                    <th>No.</td>
                    <th>School ID</th>
                    <th>School Name</th>
                    <th>Address</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                    <% @schools.each.with_index do |item, index| %>
                        <tr class="tr">
                            <td>
                                <%= "#{index+1}." %>
                            </td>
                            <td>
                                <%= item.school_number %>
                            </td>
                            <td>
                                <%= item.name %>
                            </td>
                            <td>
                                <%= item.address %>
                            </td>
                            <td>
                                <button id="delete" data-id="<%= item.id %>" class="btn btn-danger">Delete</button>
                            </td>
                        </tr>
                    <%end%>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal fade" id="new_school" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Add New schools</h4>
        <button type="button" class="close" data-dismiss="modal"aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag({:action=>'index'},{:method=>'post', :id=>'form_new_school'}) do %>
            <div class="form-group">
                <%= label_tag(:school_number, "School ID") %>
                <%= text_field_tag(:school_number, '', class: 'form-control', placeholder: 'School ID') %>
            </div>
            <div class="form-group">
                <%= label_tag(:name, 'School Name') %>
                <%= text_field_tag(:name, '', class: 'form-control', placeholder: 'School Name') %>
            </div>
            <div class="form-group">
                <%= label_tag(:address, 'Address') %>
                <%= text_area_tag(:address, '', class: 'form-control') %>
            </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default"data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary info" id="submit_new_school">Save</button>
      </div>
    </div>
  </div>
</div>

app/views/students/index.html.erb
<%= render 'templates/navigation' %>
<div class="container p-4">
    <h2>Data Students</h2>
    <div class="card">
        <div class="card-header">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#new_student" id="button">Add New Student</button>
        </div>
        <div class="card-body">
            <table class="table table_students">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>NIS</th>
                        <th>Name</th>
                        <th>class</th>
                        <th>Address</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <% @students.each.with_index do |item, index| %>
                        <tr>
                            <td><%= index+1 %>.</td>
                            <td><%= item.nis %></td>
                            <td><%= item.user.name %></td>
                            <td><%= item.school.name %></td>
                            <td><%= item.user.address %></td>
                            <td>
                                <button class="btn btn-danger" id="delete" data-id="<%= item.id %>">
                                    Delete
                                </button>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal fade" id="new_student" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Add New Student</h4>
        <button type="button" class="close" data-dismiss="modal"aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag({:action=>'index'}, {:method=>'post', :id=>'form_new_student'}) do %>
            <div class="form-group">
                <%= label_tag(:nis, 'NIS') %>
                <%= text_field_tag(:nis, '', class: 'form-control', placeholder: 'NIS') %>
            </div>
            <div class="form-group">
                <%= label_tag(:user_id, 'User Name') %>
                <select name="user_id" class="form-control">
                    <% @users.each do |item| %>
                        <option value="<%= item.id %>"><%= item.name %></option>
                    <% end %>
                </select>
            </div>
            <div class="form-group">
                <%= label_tag(:school_id, "School") %>
                <select name="school_id" class="form-control">
                    <% @schools.each do |item| %>
                        <option value="<%= item.id %>"><%= item.name %></option>
                    <% end %>
                </select>
            </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default"data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary info" id="submit_new_student">Save</button>
      </div>
    </div>
  </div>
</div>

app/views/templates/_navigation.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/users/index">Users</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/students/index">Students</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/schools/index">Schols</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/users/edit.html.erb
<div class="container p-5">
  <div class="row">
    <div class="col-md-4 offset-md-4">
        <h2>Edit User</h2>
        <hr/>
        <%= form_tag({:action=>'update'},{:method=>'post'}) do %>
            <%= hidden_field_tag(:id, @user.id) %>
            <div class="form-group">
                <%= label_tag(:name, "User Name")%>
                <%= text_field_tag(:name, @user.name, class: 'form-control', placeholder: 'User Name')%>
            </div>
            <div class="form-group">
                <%= label_tag(:phone_number, "Phone Number")%>
                <%= text_field_tag(:phone_number, @user.phone_number, class: 'form-control', placeholder: 'Phone Number')%>
            </div>
            <div class="form-group">
                <%= label_tag(:address, "Address") %>
                <%= text_area_tag(:address, @user.address, class: 'form-control') %>
            </div>
            <hr/>
            <div class="form-group">
                <%= submit_tag("Submit", class: 'btn btn-success') %>
                <%= link_to 'Cancel', users_index_path, class: 'btn btn-danger' %>
            </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'templates/navigation' %>
<div class="container p-4">
    <h2>Data Users</h2>
    <div class="card">
        <div class="card-header">
            <%= link_to 'Add Users', users_new_path, class: 'btn btn-link' %>   
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#new_user" id="button">Add New Users</button>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th>No.</td>
                    <th>Name</th>
                    <th>Phone Number</th>
                    <th>Address</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                    <% @users.each.with_index do |item, index| %>
                        <tr>
                            <td>
                                <%= "#{index+1}." %>
                            </td>
                            <td>
                                <%= item.name %>
                            </td>
                            <td>
                                <%= item.phone_number %>
                            </td>
                            <td>
                                <%= item.address %>
                            </td>
                            <td>
                                <%= link_to 'Edit', users_edit_path(:id=>item.id), class: "btn btn-warning" %>
                                <%= link_to 'Delete', users_destroy_path(:id=>item.id), class: "btn btn-danger" %>
                            </td>
                        </tr>
                    <%end%>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal fade" id="new_user" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Add New Users</h4>
        <button type="button" class="close" data-dismiss="modal"aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag({:action=>'index'},{:method=>'post', :id=>'form_new_user'}) do %>
            <div class="form-group">
                <%= label_tag(:name, 'User Name') %>
                <%= text_field_tag(:name, '', class: 'form-control', placeholder: 'User Name') %>
            </div>
            <div class="form-group">
                <%= label_tag(:phone_number, "Phone Number") %>
                <%= text_field_tag(:phone_number, '', class: 'form-control', placeholder: 'Phone Number') %>
            </div>
            <div class="form-group">
                <%= label_tag(:address, 'Address') %>
                <%= text_area_tag(:address, '', class: 'form-control') %>
            </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default"data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary info" id="submit_new_user">Save</button>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container p-5">
  <div class="row">
    <div class="col-md-4 offset-md-4">
        <h2>New User</h2>
        <hr/>
        <%= form_tag({:action=>'create'},{:method=>'post'}) do %>
            <div class="form-group">
                <%= label_tag(:name, "User Name")%>
                <%= text_field_tag(:name, '', class: 'form-control', placeholder: 'User Name')%>
            </div>
            <div class="form-group">
                <%= label_tag(:phone_number, "Phone Number")%>
                <%= text_field_tag(:phone_number, '', class: 'form-control', placeholder: 'Phone Number')%>
            </div>
            <div class="form-group">
                <%= label_tag(:address, "Address") %>
                <%= text_area_tag(:address, '', class: 'form-control') %>
            </div>
            <hr/>
            <div class="form-group">
                <%= submit_tag("Submit", class: 'btn btn-success') %>
                <%= link_to 'Cancel', users_index_path, class: 'btn btn-danger' %>
            </div>
        <% end %>
    </div>
  </div>
</div>